/**
 * Next.js scaffold template files
 */

import type { ScaffoldFile } from './react';

export const nextjsScaffold: ScaffoldFile[] = [
  {
    path: 'app/page.jsx',
    name: 'page.jsx',
    content: `export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to Next.js</h1>
        <p className="text-gray-600">Get started by editing this page.</p>
      </div>
    </main>
  );
}`,
    language: 'jsx',
    isMain: true,
  },
  {
    path: 'app/layout.jsx',
    name: 'layout.jsx',
    content: `export const metadata = {
  title: 'Next.js App',
  description: 'Generated by OpenIdea',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
    language: 'jsx',
    isMain: false,
  },
];
