import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getCurrentUser, ensureUserInDb } from '@/lib/auth';

/**
 * POST /api/app-projects/[id]/export/github
 *
 * Exports the project to a new GitHub repository.
 * Expects body: { token: string, repoName?: string, isPrivate?: boolean }
 * The token is a GitHub Personal Access Token with `repo` scope.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
    }

    await ensureUserInDb(user);

    const prismaUser = await prisma.user.findUnique({
      where: { supabaseId: user.id },
    });
    if (!prismaUser) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    const { id } = await params;

    const project = await prisma.appProject.findUnique({
      where: { id },
      include: { files: true },
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }
    if (project.ownerId !== prismaUser.id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await req.json();
    const { token, repoName, isPrivate } = body as {
      token: string;
      repoName?: string;
      isPrivate?: boolean;
    };

    if (!token || typeof token !== 'string') {
      return NextResponse.json(
        { error: 'GitHub Personal Access Token is required' },
        { status: 400 }
      );
    }

    // Sanitise repo name
    const safeName = (repoName || project.title || 'app-project')
      .replace(/[^a-zA-Z0-9_.-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 100)
      || 'app-project';

    // ------------------------------------------------------------------
    // 1. Create repository
    // ------------------------------------------------------------------
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: safeName,
        description: project.description || `Generated by Open Idea Studio`,
        private: isPrivate ?? false,
        auto_init: true, // creates default branch with README
      }),
    });

    if (!createRepoRes.ok) {
      const err = await createRepoRes.json().catch(() => ({}));
      const msg = (err as any)?.message || 'Failed to create repository';
      if (createRepoRes.status === 401) {
        return NextResponse.json(
          { error: 'Invalid GitHub token. Make sure it has the "repo" scope.' },
          { status: 401 }
        );
      }
      if (createRepoRes.status === 422 && msg.includes('already exists')) {
        return NextResponse.json(
          { error: `Repository "${safeName}" already exists. Choose a different name.` },
          { status: 409 }
        );
      }
      return NextResponse.json({ error: msg }, { status: createRepoRes.status });
    }

    const repoData = (await createRepoRes.json()) as {
      full_name: string;
      html_url: string;
      default_branch: string;
    };
    const { full_name: fullName, html_url: htmlUrl, default_branch: defaultBranch } = repoData;

    // ------------------------------------------------------------------
    // 2. Get latest commit SHA (from auto-init) for tree base
    // ------------------------------------------------------------------
    const refRes = await fetch(
      `https://api.github.com/repos/${fullName}/git/ref/heads/${defaultBranch}`,
      { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }
    );
    if (!refRes.ok) {
      return NextResponse.json(
        { error: 'Failed to read repository reference. The repo was created but file push failed.' },
        { status: 502 }
      );
    }
    const refData = (await refRes.json()) as { object: { sha: string } };
    const baseCommitSha = refData.object.sha;

    // ------------------------------------------------------------------
    // 3. Create blobs for each file
    // ------------------------------------------------------------------
    const files = project.files || [];
    if (files.length === 0) {
      return NextResponse.json({
        success: true,
        repoUrl: htmlUrl,
        message: 'Repository created but no files to push.',
      });
    }

    const treeEntries: { path: string; mode: string; type: string; sha: string }[] = [];

    // Add a package.json if it doesn't exist
    const hasPackageJson = files.some((f) => f.path === 'package.json');
    const allFiles = hasPackageJson
      ? files
      : [
          {
            path: 'package.json',
            content: JSON.stringify(
              {
                name: safeName,
                private: true,
                version: '0.0.1',
                type: 'module',
                scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
                dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
                devDependencies: { '@vitejs/plugin-react': '^4.3.4', vite: '^6.0.0' },
              },
              null,
              2
            ),
          },
          ...files,
        ];

    for (const file of allFiles) {
      const blobRes = await fetch(`https://api.github.com/repos/${fullName}/git/blobs`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          content: file.content,
          encoding: 'utf-8',
        }),
      });

      if (!blobRes.ok) continue; // skip failed blobs
      const blobData = (await blobRes.json()) as { sha: string };
      treeEntries.push({
        path: file.path,
        mode: '100644',
        type: 'blob',
        sha: blobData.sha,
      });
    }

    // ------------------------------------------------------------------
    // 4. Create tree
    // ------------------------------------------------------------------
    const treeRes = await fetch(`https://api.github.com/repos/${fullName}/git/trees`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        base_tree: baseCommitSha,
        tree: treeEntries,
      }),
    });

    if (!treeRes.ok) {
      return NextResponse.json(
        { error: 'Failed to create file tree on GitHub', repoUrl: htmlUrl },
        { status: 502 }
      );
    }
    const treeData = (await treeRes.json()) as { sha: string };

    // ------------------------------------------------------------------
    // 5. Create commit
    // ------------------------------------------------------------------
    const commitRes = await fetch(`https://api.github.com/repos/${fullName}/git/commits`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: `Initial commit from Open Idea Studio\n\nProject: ${project.title || safeName}`,
        tree: treeData.sha,
        parents: [baseCommitSha],
      }),
    });

    if (!commitRes.ok) {
      return NextResponse.json(
        { error: 'Failed to create commit on GitHub', repoUrl: htmlUrl },
        { status: 502 }
      );
    }
    const commitData = (await commitRes.json()) as { sha: string };

    // ------------------------------------------------------------------
    // 6. Update branch reference to point to new commit
    // ------------------------------------------------------------------
    const updateRefRes = await fetch(
      `https://api.github.com/repos/${fullName}/git/refs/heads/${defaultBranch}`,
      {
        method: 'PATCH',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ sha: commitData.sha }),
      }
    );

    if (!updateRefRes.ok) {
      return NextResponse.json(
        { error: 'Files committed but failed to update branch reference', repoUrl: htmlUrl },
        { status: 502 }
      );
    }

    // ------------------------------------------------------------------
    // 7. Save github URL to project
    // ------------------------------------------------------------------
    await prisma.appProject.update({
      where: { id },
      data: { config: { ...(project.config as any || {}), githubUrl: htmlUrl } },
    });

    return NextResponse.json({
      success: true,
      repoUrl: htmlUrl,
      repoName: fullName,
      filesCommitted: treeEntries.length,
    });
  } catch (error) {
    console.error('GitHub export error:', error);
    return NextResponse.json(
      { error: 'An unexpected error occurred during GitHub export' },
      { status: 500 }
    );
  }
}
