#!/bin/bash

# Helper script to guide users on getting auth token
# This script provides instructions and examples

echo "=========================================="
echo "How to Get Your Authentication Token"
echo "=========================================="
echo ""
echo "Method 1: Browser DevTools (Recommended)"
echo "----------------------------------------"
echo "1. Sign in to http://localhost:3000/auth"
echo "2. Open DevTools (F12)"
echo "3. Go to Application tab (Chrome) or Storage tab (Firefox)"
echo "4. Expand 'Cookies' → click 'http://localhost:3000'"
echo "5. Find 'sb-access-token' cookie"
echo "6. Copy the VALUE (it's a long JWT string)"
echo ""
echo "Method 2: Browser Console"
echo "----------------------------------------"
echo "1. Open DevTools Console (F12)"
echo "2. Run this command:"
echo ""
echo "   document.cookie.split('; ').find(row => row.startsWith('sb-access-token='))?.split('=')[1]"
echo ""
echo "3. Copy the output"
echo ""
echo "Example Usage:"
echo "----------------------------------------"
echo "TOKEN=\"your-token-here\""
echo ""
echo "curl -X POST http://localhost:3000/api/community/groups \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Cookie: sb-access-token=\$TOKEN\" \\"
echo "  -d '{\"name\": \"Test Group\", \"isPublic\": true}'"
echo ""
echo "=========================================="
echo ""
echo "💡 Tip: The token is a JWT (long string starting with 'eyJ...')"
echo "💡 Tip: Tokens expire - if you get 'Not authenticated', get a new one"
echo ""

